pkgmk.in: tiny code refactoring

diff --git a/pkgmk.in b/pkgmk.in
--- a/pkgmk.in
+++ b/pkgmk.in
@@ -119,7 +119,9 @@ download_git() {
 			info "Clone $_BRANCH branch from '$_URL'"
 			git clone --depth=1 $_URL -b $_BRANCH $_DIR
 		fi
-		return
+	else
+		error "Unknown git url: '$1'. Missing branch?"
+		exit $E_DOWNLOAD
 	fi
 }
 
@@ -197,7 +199,11 @@ download_source() {
 	local SRCPATH SRCNAME SRCTYPE
 	for SRCPATH in ${source[@]}; do
 		SRCNAME=`get_filename $SRCPATH`
-		[[ "$SRCPATH" =~ ^git+ ]] && SRCTYPE="git" || SRCTYPE="file"
+		if [[ "$SRCPATH" =~ ^git+ ]]; then
+			SRCTYPE="git"
+		else
+			SRCTYPE="file"
+		fi
 
 		if [ ! -e $SRCNAME ]; then
 			if [ "$SRCNAME" = "$SRCPATH" ]; then
@@ -205,7 +211,11 @@ download_source() {
 				exit $E_DOWNLOAD
 			else
 				if [ "$PKGMK_DOWNLOAD" = "yes" ]; then
-					[[ "$SRCTYPE" = "git" ]] && download_git $SRCPATH || download_file $SRCPATH
+					if [[ "$SRCTYPE" = "git" ]]; then
+						download_git  $SRCPATH
+					else
+						download_file $SRCPATH
+					fi
 				else
 					error "Source $SRCTYPE '$SRCNAME' not found (use option -d to download)."
 					exit $E_DOWNLOAD
@@ -250,7 +260,7 @@ make_md5sum() {
 
 	if [ "$source" ]; then
 		for FILE in ${source[@]}; do
-			LOCAL_FILENAMES="$LOCAL_FILENAMES `get_filename $FILE`"
+			LOCAL_FILENAMES="$LOCAL_FILENAMES $(get_filename $FILE)"
 		done
 
 		md5sum $LOCAL_FILENAMES | sed -e 's|  .*/|  |' | sort -k 2
@@ -326,7 +336,8 @@ strip_files() {
 		FILTER="cat"
 	fi
 
-	find . -type f -printf "%P\n" | $FILTER                   \
+	find . -type f -printf "%P\n"                             \
+		| $FILTER                                         \
 		| xargs -r -L10 -P${JOBS:-1}                      \
 			file --no-buffer --separator '>'          \
 			-e apptype -e ascii -e encoding -e tokens \
@@ -526,8 +537,8 @@ update_footprint() {
 
 build_needed() {
 	local FILE RESULT
-
 	RESULT="yes"
+
 	if [ -f $TARGET ]; then
 		RESULT="no"
 		for FILE in $PKGMK_PKGFILE ${source[@]}; do
